tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0c2965",
        "on-primary": "#ffffff",
        "primary-container": "#28407c",
        "on-primary-container": "#97aef1",
        "secondary": "#7a5900",
        "on-secondary": "#ffffff",
        "secondary-container": "#fec336",
        "on-secondary-container": "#6f5100",
        "tertiary": "#00304c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00476e",
        "on-tertiary-container": "#57b8ff",
        "background": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "surface-variant": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#444650",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#757681",
        "outline-variant": "#c5c6d1",
        "harvest-gold": "#93CAFF",
        "scientific-blue": "#28407C",
        "clinical-white": "#F8FAFC",
        "slate-dark": "#0F172A",
      },
      fontFamily: {
        "display": ["Hanken Grotesk", "sans-serif"],
        "headline": ["Hanken Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "button": ["14px", { lineHeight: "20px", fontWeight: "600" }],
      },
      spacing: {
        "container-max": "1280px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "gutter": "24px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    }
  }
};
